import Header from "./Header";
import Head from "next/head";
import { createTheme, ThemeProvider } from "@mui/material";
import { ReactElement } from "react";
import { green } from "@mui/material/colors";

const theme = createTheme({
  palette: {
    primary: {
      main: green[500]
    }
  },

  typography: {
    fontSize: 16
  }
})

export const Layout = ({children}: {children: ReactElement}) => {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Subsc Square</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="contents">
        <Header />
  
        <main>
          {children}
        </main>
      </div>
    </ThemeProvider>
  )
}